# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

use_frameworks!

target 'gamves' do 

  pod 'DeviceKit'

  pod 'Parse'

  pod 'Bolts-Swift', :git => 'https://github.com/BoltsFramework/Bolts-Swift', :commit => 'e9baa72d04521c3b25ef4fa6fef12b340953ee02'

  pod 'ParseLiveQuery'
  
  pod 'Floaty', '~> 4.0.1'

  pod 'SKPhotoBrowser', '~> 5.1.0'

  pod 'PopupDialog', '~> 0.6.0'

  pod 'NVActivityIndicatorView' 
  
  pod 'DownPicker'
  
  pod 'Alamofire'
  
  pod 'SwiftyJSON'
  
  pod 'UITextView+Placeholder'
  
  #pod 'AWSS3', :git => 'https://github.com/aws/aws-sdk-ios.git', :branch => 'xcode-10'

  #pod 'AWSS3', :git => 'https://github.com/aws/aws-sdk-ios.git', :tag => 'untagged-97748b31578af347f0f5'  

  pod 'AWSS3', '~> 2.6.22'

  pod 'YouTubePlayer'

  pod 'CalmParametricAnimations'

  pod 'SDWebImage'
  
  pod 'IGColorPicker' 
  
  pod 'PulsingHalo'
 
  pod 'ISEmojiView'
  
  pod 'RSKImageCropper'

  pod 'Atributika'
  
  pod 'SwiftHash'  

  pod 'DRPLoadingSpinner'

  pod 'TaskQueue'
  
end
