# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

use_frameworks!

target 'gamves' do 

  pod 'DeviceKit'

  pod 'Parse'

  pod 'Bolts-Swift', :git => 'https://github.com/BoltsFramework/Bolts-Swift', :commit => 'e9baa72d04521c3b25ef4fa6fef12b340953ee02'

  pod 'ParseLiveQuery'
  
  pod 'Floaty', '~> 4.0.1'

  pod 'SKPhotoBrowser', '~> 5.1.0'

  pod 'PopupDialog', '~> 0.6.0'

  pod 'NVActivityIndicatorView', '~> 4.0.1'
  
  pod 'DownPicker'
  
  pod 'Alamofire'
  
  pod 'SwiftyJSON'
  
  pod 'UITextView+Placeholder'  
  
  pod 'AWSS3', '~> 2.6.32'

  pod 'YouTubePlayer'

  pod 'CalmParametricAnimations'

  pod 'SDWebImage'
  
  pod 'IGColorPicker' 
  
  pod 'PulsingHalo'
 
  pod 'ISEmojiView'
  
  pod 'RSKImageCropper'

  pod 'Atributika'
  
  pod 'SwiftHash'  

  pod 'DRPLoadingSpinner'

  pod 'TaskQueue'   

end

target 'shared' do

  pod 'Parse'

  pod 'Bolts-Swift', :git => 'https://github.com/BoltsFramework/Bolts-Swift', :commit => 'e9baa72d04521c3b25ef4fa6fef12b340953ee02'

  pod 'ParseLiveQuery'

end
