# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

use_frameworks!

target 'gamves' do

  pod 'ParseLiveQuery'

  pod 'DeviceKit'

  pod 'Parse'

  pod 'Parse'

  pod 'Bolts-Swift', :git => 'https://github.com/BoltsFramework/Bolts-Swift', :commit => 'e9baa72d04521c3b25ef4fa6fef12b340953ee02'
  
  pod 'Floaty' 
  
  pod 'NVActivityIndicatorView'
  
  pod 'PopupDialog'
  
  pod 'DownPicker'
  
  pod 'Alamofire'
  
  pod 'SwiftyJSON'
  
  pod 'UITextView+Placeholder'
  
  pod 'AWSS3'
  
  pod 'YouTubePlayer'

  pod 'CalmParametricAnimations'
  pod 'SDWebImage'
  
  pod 'IGColorPicker' 
  
  pod 'PulsingHalo'
 
  pod 'ISEmojiView'
  
  pod 'RSKImageCropper'

  pod 'PopupDialog'

  pod 'Atributika'
  
  pod 'SwiftHash'

  pod 'SKPhotoBrowser'

  pod 'DRPLoadingSpinner'

  pod 'TaskQueue'
  
end
