# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!

target 'gamvesparents' do 
  
  pod 'DeviceKit'

  pod 'Parse'

  #pod 'Bolts-Swift'

  pod 'ParseLiveQuery'
  
  pod 'Floaty', '~> 4.0.1'  
  
  pod 'DownPicker'

  pod 'SwiftValidator', :git => 'https://github.com/jpotts18/SwiftValidator.git', :branch => 'master'
    
  pod 'BEMCheckBox'
  
  pod 'NVActivityIndicatorView', '~> 4.0.1'

  pod 'RSKImageCropper'
  
  pod 'PopupDialog', '~> 0.6.0'

  pod 'TaskQueue'
  
  pod 'youtube-ios-player-helper', '~> 0.1.4'
  
  pod 'AWSS3', '~> 2.6.32'
  
  pod 'Stripe'
  
  #pod 'SwiftPhotoGallery'
  
  pod 'ImageSlideshow' #, '~> 1.4'
  
  #pod 'MercadoPagoSDK' #, '3.7.1'
  
  pod 'ISEmojiView' 
  
  pod 'PulsingHalo'

  pod 'Alamofire'

  pod 'SwiftyJSON'

  pod 'YouTubePlayer'

  pod 'UITextView+Placeholder'

  pod 'Atributika'

  pod 'Firebase/Core'

  pod 'Fabric', '~> 1.9.0'
  pod 'Crashlytics', '~> 3.12.0'
    
end
