# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'gamvesparents' do
  
  use_frameworks!

  # Pods for gamvesparents

  pod 'DeviceKit'
  
  pod 'DownPicker'

  pod 'SwiftValidator', :git => 'https://github.com/jpotts18/SwiftValidator.git', :branch => 'master'
  
  pod 'ParseLiveQuery', :git => 'https://github.com/parse-community/ParseLiveQuery-iOS-OSX.git', :branch => 'master'
  
  pod 'BEMCheckBox'
  
  pod 'NVActivityIndicatorView'

  pod 'RSKImageCropper'
  
  pod 'Floaty', :git => 'https://github.com/kciter/Floaty.git', :tag => '4.0.0'

  pod 'PopupDialog'

  pod 'TaskQueue'
  
  pod 'youtube-ios-player-helper', '~> 0.1.4'
  
  # pod 'MercadoPagoSDK', '3.7.1'
    
end
